=== zsirosnikolett/MOIZHL_XMLGyak/MOIZHL_1012/ZSN_orarend1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="orarend" type="orarendTipus"/>
		<xs:complexType name="orarendTipus">
			<xs:sequence>
				<xs:element name="ora" type="oraTipus" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType >
		<xs:complexType name="oraTipus">
			<xs:sequence>
				<xs:element name="targy" type="targyTipus"/>
				<xs:element name="idopont" type="idopontTipus"/>
				<xs:element name="helyszin" type="xs:string" />
				<xs:element name="oktato" type="oktatoTipus"/>
				<xs:element name="szak" type="xs:string" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="tipus" type="xs:string" use="required" />
		</xs:complexType >

		<xs:complexType name="targyTipus">
		
				<xs:attribute name="nev" type="xs:string" use="required" />

		</xs:complexType>

		<xs:complexType name="idopontTipus">
			<xs:sequence>
				<xs:element name="nap" type="xs:string" />
				<xs:element name="tol" type="xs:string" />
				<xs:element name="ig" type="xs:string" />
			</xs:sequence>

		</xs:complexType>


		<xs:complexType name="oktatoTipus">
			<xs:attribute name="nev" type="xs:string" use="optional" />
		</xs:complexType>




</xs:schema>

=== zsirosnikolett/MOIZHL_XMLGyak/MOIZHL_1012/ZSN_orarend1.xml
<?xml version="1.0" encoding="utf-8"?>

<orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:noNamespaceSchemaLocation="ZSN_orarend1.xsd">

	<ora id="1" tipus="gyakorlat" >
		<targy nev="Automaták és formális nyelvek"/>
		<idopont >

			<nap>Hétfo</nap>
			<tol>16:00</tol>
			<ig>18:00</ig>
		</idopont>
		<helyszin>XII előadó</helyszin>
		<oktato nev="Veres Laura"/>
		<szak>Programtervező</szak>

	</ora>

	<ora id="2" tipus="gyakorlat" >
		<targy nev="Adatkezelés XML-ben"/>
		<idopont >

			<nap>Kedd</nap>
			<tol>12:00</tol>
			<ig>16:00</ig>
		</idopont>
		<helyszin>I előadó</helyszin>
		<oktato nev="Bednarik László"/>
		<szak>Programtervező</szak>

	</ora>

	<ora id="3" tipus="elmelet" >
		<targy nev="Vállalati információs rendszerek fejlesztése"/>
		<idopont >

			<nap>Szerda</nap>
			<tol>16:00</tol>
			<ig>20:00</ig>
		</idopont>
		<helyszin>IX előadó</helyszin>
		<oktato nev="Dr. Sasvári Péter László"/>
		<szak>Programtervező</szak>
	</ora>

	<ora id="4" tipus="elmelet" >
		<targy nev="Szakdolgozatkészítés I."/>
		<idopont >
			<nap>Csutortok</nap>
			<tol>16:00</tol>
			<ig>17:00</ig>
		</idopont>
		<helyszin>I előadó</helyszin>
		<oktato nev="Karácsony Zsolt "/>
		<szak>Programtervező</szak>
	</ora>

	<ora id="5" tipus="gyakorlat" >
		<targy nev="Testnevelés I."/>
		<idopont >
			<nap>Pentek</nap>
			<tol>10:00</tol>
			<ig>18:00</ig>
		</idopont>
		<helyszin>UFO</helyszin> 
		<oktato nev="Minta Aladár"/>
		<szak>Programtervező</szak>

	</ora>



</orarend>
