=== zsirosnikolett/MOIZHL_XMLGyak/MOZIHL_0928/ZSN_konyv.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT könyvek (könyv*)>
<!ELEMENT könyv (cim, kiadasi_ev,kiado,szerzo,abstract*)>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadasi_ev (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
<!ELEMENT abstract (#PCDATA)>

=== zsirosnikolett/MOIZHL_XMLGyak/MOIZHL_0928/ZSN_konyv.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE könyvek SYSTEM "ZSN_konyv.dtd">

<könyvek>
	<könyv id="x1">
		<cim >Excel 2019</cim>
		<kiadasi_ev>2021</kiadasi_ev>
		<kiado>Taramix kiado KFT</kiado>
		<szerzo>Szabó Ildikó</szerzo>
		<abstract/>
	</könyv>
	
	<könyv id="x2">
		<cim >Word 2019</cim>
		<kiadasi_ev>2021</kiadasi_ev>
		<kiado>Taramix kido KFT</kiado>
		<szerzo>Dávid Krisztina</szerzo>
		<abstract/>
	</könyv>
	
	<könyv id="x3">
		<cim>PowerPoint 2019 zsebkönyv</cim>
		<kiadasi_ev>2019</kiadasi_ev>
		<kiado>BBS-INFO KÖNYVK. ÉS INFORM. KFT.</kiado>
		<szerzo>Bártfai Tamás</szerzo> 
		<abstract/>
	</könyv>
	
</könyvek>
